<?php

namespace TonoBundle\Repository;

/**
 * IngredientRecetteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientRecetteRepository extends \Doctrine\ORM\EntityRepository
{
}
