<?php

namespace TonoBundle\Repository;
use TonoBundle\Entity\Recette;
use TonoBundle\Entity\Meal;


/**
 * MealRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MealRepository extends \Doctrine\ORM\EntityRepository {
   
    public function clear_week() {
        $qb = $this->createQueryBuilder('m');
        $query = $qb->delete('TonoBundle:Meal', 'm')
                ->getQuery();
        $query->execute();
    }
    
    public function deleteFromId($id){
        $qb = $this->createQueryBuilder('m');
        $query = $qb->delete('TonoBundle:Meal', 'm')
                ->where('m.id = :id')
                ->setParameter('id',$id)
                ->getQuery();
        $query->execute();
    }
    
    
    
    public function getActualWeek()
    {
        $qb = $this->createQueryBuilder('m');
        $query = $qb->select('m')
                ->addOrderBy('m.slot', 'ASC')   
                ->getQuery()   
                ->getResult();
       return($query);
    }
    
    
}
