<?php

namespace TonoBundle\Repository;

/**
 * RecetteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecetteRepository extends \Doctrine\ORM\EntityRepository {

    public function findAll()
    {
        return $this->findBy(array(), array('lourd' => 'ASC'));
    }
    public function get_random($exception = array(),$lourdeur) {

        $count = $this
                ->createQueryBuilder('r')
                ->select('COUNT(r)')
                ->where('r.id NOT IN (:dejacooked)')
                ->andWhere('r.lourd = :lourdeur')
                ->andWhere('r.disabled = 0')
                ->setParameter('dejacooked',$exception)
                ->setParameter('lourdeur',$lourdeur)
                ->getQuery()
                ->getSingleScalarResult();
        
         //exit($count.' + '.$lourdeur);


        $queryBuilder = $this
                ->createQueryBuilder('r')
                ->where('r.id NOT IN (:dejacooked)')
                ->andWhere('r.lourd = :lourdeur')
                ->setParameter('dejacooked',$exception)
                ->setParameter('lourdeur',$lourdeur)
                ->setFirstResult(rand(0, $count - 1))
                ->setMaxResults(1)
                ->getQuery()
                ->getResult();
        
        if(!$queryBuilder) 
        {
             return(null);
        }
        return $queryBuilder[0];
                        
                       
    }
    
    public function findRecetteFromIngredients(array $ingredients)
    {
        foreach($ingredient as $ingredient)
        {
           $recettes = $this
                ->createQueryBuilder('r')
                ->where('r.ingredients = :ingredient')
                ->setParameter('ingredient',$ingredient)
                ->execute();
           
        }
    }
    
   

}
