<?php

namespace TonoBundle\Repository;

/**
 * SlotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlotRepository extends \Doctrine\ORM\EntityRepository
{
     public function findAll()
    {
        return $this->findBy(array(), array('position' => 'ASC'));
    }
}
